services:
  EventSQL:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /mnt/d/Coding Area/Semester 6/pythonProject/project-soa/event_service/eventSQL:/docker-entrypoint-initdb.d
    networks:
      - EventNet
  EventSvc:
    build: ./EventSvc/
    image: event_svc
    ports:
      - 5600:5600
    networks:
      - OrganizerNet
      - EventNet
    depends_on: 
      EventSQL:
        condition: service_started
  EventCons:
    build: ./EventCons/
    image: event_cons
    networks:
      - OrganizerNet
      - EventNet
    depends_on: 
      EventSQL:
        condition: service_started

networks:
  OrganizerNet:
  EventNet: