services:
  EventSQL:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./eventSQL/:/docker-entrypoint-initdb.d
    networks:
      - EventNet
  EventSvc:
    build: ./EventSvc/
    image: event_svc
    ports:
      - 5500:5500
    networks:
      - OrganizerNet
      - EventNet
    depends_on: 
      EventSQL:
        condition: service_started
  EventCons:
    build: ./EventCons/
    image: event_cons
    networks:
      - OrganizerNet
      - EventNet
    depends_on: 
      EventSQL:
        condition: service_started

networks:
  OrganizerNet:
  EventNet: