FROM python:3.10.11-slim-bullseye

WORKDIR /app
COPY ./event.py .
COPY ./event_producer.py .

RUN python -m pip install flask
RUN python -m pip install pika
RUN python -m pip install mysql-connector-python
RUN python -m pip install flask_cors

EXPOSE 5600/tcp

CMD python -m flask --app event run --host=0.0.0.0 -p 5600
