services:
  OrderSQL:
    image: mysql
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./orderSQL/:/docker-entrypoint-initdb.d
    networks:
      - OrderNet
  OrderSvc:
    build: ./orderSvc/
    image: order_svc
    ports:
      - 5530:5530
    networks:
      - OrganizerNet
      - OrderNet
    depends_on: 
      OrderSQL:
        condition: service_started
  OrderCons:
    build: ./orderCons/
    image: order_cons
    networks:
      - OrganizerNet
      - OrderNet
    depends_on: 
      OrderSQL:
        condition: service_started

networks:
  OrganizerNet:
  OrderNet: