FROM python:3.10.11-slim-bullseye

WORKDIR /app
COPY ./client.py .
COPY ./client_producer.py .

RUN python -m pip install flask
RUN python -m pip install pika
RUN python -m pip install mysql-connector-python

EXPOSE 5500/tcp

CMD python -m flask --app client run --host=0.0.0.0 -p 5500
