services:
  EventSQL:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /mnt/e/uassoa/Event/EventSQL:/docker-entrypoint-initdb.d
    networks:
      - EventNet
  EventSvc:
    build: ./EventSvc/
    image: event_svc
    ports:
      - 5600:5600
    networks:
      - EoNet
      - EventNet
    depends_on: 
      EventSQL:
        condition: service_started
  EventCons:
    build: ./EventCons/
    image: event_cons
    networks:
      - EoNet
      - EventNet
    depends_on: 
      EventSQL:
        condition: service_started

networks:
  EoNet:
  EventNet: