services:
  LoginSQL:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./loginSQL/:/docker-entrypoint-initdb.d
    networks:
      - LoginNet
  LoginSvc:
    build: ./loginSvc/
    image: login_svc
    ports:
      - 5520:5520
    networks:
      - OrganizerNet
      - LoginNet
    depends_on: 
      LoginSQL:
        condition: service_started
  LoginCons:
    build: ./loginCons/
    image: login_cons
    networks:
      - OrganizerNet
      - LoginNet
    depends_on: 
      LoginSQL:
        condition: service_started

networks:
  OrganizerNet:
  LoginNet: