services:
  clientSQL:
    image: mysql
    ports:
      - 3305:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./clientSQL/:/docker-entrypoint-initdb.d
    networks:
      - ClientNet
  ClientSvc:
    build: ./clientSvc/
    image: client_svc 
    ports:
      - 5500:5500
    networks:
      - OrganizerNet
      - ClientNet
    depends_on: 
      clientSQL:
        condition: service_started

networks:
  OrganizerNet:
  ClientNet:
